import localFont from "next/font/local";
import "../public/globals.css";

const AnonymousPro = localFont({
  src: "../public/fonts/Anonymous_Pro.ttf",
  variable: "--font-anonymous-pro",
  weight: "100 900",
});

export const metadata = {
  title: "PravoBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${AnonymousPro.variable} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
